### ISSUE TITLE
security code uncheck any site error how it fix please

### ISSUE THREAD

**Issue by droandres** [reboot13-git/cc-checker#28]

**Comment by droandres** [comment]
![Screenshot_20200508-030209_Firefox](https://user-images.githubusercontent.com/64325935/81336248-8dd4ea00-90db-11ea-92a8-fcc75cf79bab.jpg)

**Comment by YashvirTheCarder** [comment]
hello bro what kind of proxies are you using for checking free or paid

**Comment by Avdhesh30** [comment]
Inbox me on telegram @profesorrabii let's talk about the cc checkers and other stuffs

**Comment by MrZa3Ter** [comment]
Need on Proxies Daed

**Comment by droandres** [comment]
Its free proxy

**Comment by MrZa3Ter** [comment]
i try free but i have some error can you help me

**Comment by reboot13-git** [comment]
thats not my api
