### ISSUE TITLE
 Proxy Dead / Error Not Listed 

### ISSUE THREAD

**Issue by MrZa3Ter** [reboot13-git/cc-checker#30]
![image](https://user-images.githubusercontent.com/65403705/82053095-471f5b00-96ac-11ea-8a63-be850c9d6ab9.png)

**Comment by reboot13-git** [comment]
use good proxies

**Comment by Maxali12** [comment]
Proxy Dead / Error Not Listed ♛ 𝕽𝖊𝖇𝖔𝖔𝖙 ♛ ♛


Why sir?
