### ISSUE TITLE
Optimizing code

### ISSUE THREAD

**Issue by hoangvu12** [reboot13-git/cc-checker#45]
Hi, I'm not that good at making these such _cc checker_. But, the code made me really annoying seems the author don't know how to write proper code to make developers can easily understand. Like you can split those into different functions.

If you want, I can try to improve this damn up. And for anyone just start try to make these _cc checker_. You better learn how PHP works first, learn basic before get into this, or you just wasting your time

**Comment by reboot13-git** [comment]
#rule 1 
If its working don't touch it
If you don't want to use
just ignore

Well it's working for other

**Comment by hoangvu12** [comment]
I'm trying to be gentle here, refactor your code is the best way to improve your coding. Since you don't want to so I don't mind
